# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 800)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(106, 110, 113);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(64, 66, 68);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(20, 10, 20, 10)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineFunction = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineFunction.sizePolicy().hasHeightForWidth())
        self.lineFunction.setSizePolicy(sizePolicy)
        self.lineFunction.setAutoFillBackground(False)
        self.lineFunction.setStyleSheet("background-color: rgb(135, 135, 135);")
        self.lineFunction.setObjectName("lineFunction")
        self.horizontalLayout_2.addWidget(self.lineFunction)
        self.spinMinX = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinX.sizePolicy().hasHeightForWidth())
        self.spinMinX.setSizePolicy(sizePolicy)
        self.spinMinX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinMinX.setMaximum(999)
        self.spinMinX.setObjectName("spinMinX")
        self.horizontalLayout_2.addWidget(self.spinMinX)
        self.spinMaxX = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxX.sizePolicy().hasHeightForWidth())
        self.spinMaxX.setSizePolicy(sizePolicy)
        self.spinMaxX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinMaxX.setMinimum(1)
        self.spinMaxX.setMaximum(1000)
        self.spinMaxX.setObjectName("spinMaxX")
        self.horizontalLayout_2.addWidget(self.spinMaxX)
        self.spinCountPoints = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinCountPoints.sizePolicy().hasHeightForWidth())
        self.spinCountPoints.setSizePolicy(sizePolicy)
        self.spinCountPoints.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinCountPoints.setMinimum(1)
        self.spinCountPoints.setMaximum(1000)
        self.spinCountPoints.setProperty("value", 10)
        self.spinCountPoints.setObjectName("spinCountPoints")
        self.horizontalLayout_2.addWidget(self.spinCountPoints)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.listNNs = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listNNs.sizePolicy().hasHeightForWidth())
        self.listNNs.setSizePolicy(sizePolicy)
        self.listNNs.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listNNs.setAutoFillBackground(True)
        self.listNNs.setStyleSheet("alternate-background-color: rgb(64, 66, 68);\n"
"background-color: rgb(135, 135, 135);")
        self.listNNs.setObjectName("listNNs")
        self.gridLayout.addWidget(self.listNNs, 7, 2, 1, 1)
        self.labelError = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelError.sizePolicy().hasHeightForWidth())
        self.labelError.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.labelError.setFont(font)
        self.labelError.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelError.setObjectName("labelError")
        self.gridLayout.addWidget(self.labelError, 8, 2, 1, 1)
        self.labelSpeed = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSpeed.sizePolicy().hasHeightForWidth())
        self.labelSpeed.setSizePolicy(sizePolicy)
        self.labelSpeed.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelSpeed.setFont(font)
        self.labelSpeed.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSpeed.setObjectName("labelSpeed")
        self.gridLayout.addWidget(self.labelSpeed, 0, 2, 1, 1)
        self.SpeedSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpeedSlider.sizePolicy().hasHeightForWidth())
        self.SpeedSlider.setSizePolicy(sizePolicy)
        self.SpeedSlider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.SpeedSlider.setAutoFillBackground(False)
        self.SpeedSlider.setStyleSheet("selection-color: rgb(0, 170, 255);")
        self.SpeedSlider.setMinimum(1)
        self.SpeedSlider.setMaximum(10)
        self.SpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SpeedSlider.setObjectName("SpeedSlider")
        self.gridLayout.addWidget(self.SpeedSlider, 3, 2, 1, 1)
        self.plainTextErrors = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextErrors.sizePolicy().hasHeightForWidth())
        self.plainTextErrors.setSizePolicy(sizePolicy)
        self.plainTextErrors.setMaximumSize(QtCore.QSize(200, 16777215))
        self.plainTextErrors.setAutoFillBackground(True)
        self.plainTextErrors.setStyleSheet("alternate-background-color: rgb(64, 66, 68);\n"
"background-color: rgb(135, 135, 135);")
        self.plainTextErrors.setObjectName("plainTextErrors")
        self.gridLayout.addWidget(self.plainTextErrors, 9, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushPlotGraph = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.pushPlotGraph.setFont(font)
        self.pushPlotGraph.setStyleSheet("background-color:rgb(85, 170, 255);")
        self.pushPlotGraph.setObjectName("pushPlotGraph")
        self.horizontalLayout.addWidget(self.pushPlotGraph)
        self.pushTrain = QtWidgets.QPushButton(self.centralwidget)
        self.pushTrain.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.pushTrain.setFont(font)
        self.pushTrain.setAutoFillBackground(False)
        self.pushTrain.setStyleSheet("background-color:rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushTrain.setObjectName("pushTrain")
        self.horizontalLayout.addWidget(self.pushTrain)
        self.pushTrain_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushTrain_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushTrain_2.setFont(font)
        self.pushTrain_2.setAutoFillBackground(False)
        self.pushTrain_2.setStyleSheet("background-color:rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushTrain_2.setObjectName("pushTrain_2")
        self.horizontalLayout.addWidget(self.pushTrain_2)
        self.pushSop = QtWidgets.QPushButton(self.centralwidget)
        self.pushSop.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.pushSop.setFont(font)
        self.pushSop.setAutoFillBackground(False)
        self.pushSop.setStyleSheet("background-color:rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushSop.setObjectName("pushSop")
        self.horizontalLayout.addWidget(self.pushSop)
        self.pushClear = QtWidgets.QPushButton(self.centralwidget)
        self.pushClear.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushClear.setFont(font)
        self.pushClear.setAutoFillBackground(False)
        self.pushClear.setStyleSheet("background-color:rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushClear.setObjectName("pushClear")
        self.horizontalLayout.addWidget(self.pushClear)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.pushCreateNN = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushCreateNN.sizePolicy().hasHeightForWidth())
        self.pushCreateNN.setSizePolicy(sizePolicy)
        self.pushCreateNN.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.pushCreateNN.setFont(font)
        self.pushCreateNN.setAutoFillBackground(False)
        self.pushCreateNN.setStyleSheet("background-color:rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushCreateNN.setObjectName("pushCreateNN")
        self.gridLayout.addWidget(self.pushCreateNN, 4, 2, 1, 1)
        self.labelNNs = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNNs.sizePolicy().hasHeightForWidth())
        self.labelNNs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.labelNNs.setFont(font)
        self.labelNNs.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelNNs.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNNs.setObjectName("labelNNs")
        self.gridLayout.addWidget(self.labelNNs, 6, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelFunct = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFunct.sizePolicy().hasHeightForWidth())
        self.labelFunct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.labelFunct.setFont(font)
        self.labelFunct.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelFunct.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelFunct.setObjectName("labelFunct")
        self.horizontalLayout_3.addWidget(self.labelFunct)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.plotWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setAutoFillBackground(False)
        self.plotWidget.setStyleSheet("\n"
"alternate-background-color: rgb(64, 66, 68);")
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 6, 0, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuExit = QtWidgets.QMenu(self.menuBar)
        self.menuExit.setObjectName("menuExit")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionAbout_programm = QtWidgets.QAction(MainWindow)
        self.actionAbout_programm.setObjectName("actionAbout_programm")
        self.menuHelp.addAction(self.actionAuthor)
        self.menuHelp.addAction(self.actionAbout_programm)
        self.menuBar.addAction(self.menuExit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Neurol Aproximation"))
        self.labelError.setText(_translate("MainWindow", "Errors"))
        self.labelSpeed.setText(_translate("MainWindow", "Speed"))
        self.pushPlotGraph.setText(_translate("MainWindow", "Draw function"))
        self.pushTrain.setText(_translate("MainWindow", "Train"))
        self.pushTrain_2.setText(_translate("MainWindow", "Predict"))
        self.pushSop.setText(_translate("MainWindow", "Stop"))
        self.pushClear.setText(_translate("MainWindow", "Clear"))
        self.pushCreateNN.setText(_translate("MainWindow", "Create Neurol Network"))
        self.labelNNs.setText(_translate("MainWindow", "Networks list"))
        self.labelFunct.setText(_translate("MainWindow", "input function y = f(x)"))
        self.label.setText(_translate("MainWindow", "Min X"))
        self.label_2.setText(_translate("MainWindow", "Max X"))
        self.label_3.setText(_translate("MainWindow", "Count points"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAuthor.setText(_translate("MainWindow", "Author"))
        self.actionAbout_programm.setText(_translate("MainWindow", "About programm"))

